### ISSUE TITLE
[DIY]MT9V034 Tutorial：如何使用全局快门摄像头 - AleX的技术小栈

### ISSUE THREAD

**Issue by AlexYzhov** [AlexYzhov/blog_comments#27]
http://www.alexvohzy.com/post/MT9V034_Tutorial.html 

 personal technique stack

**Comment by jason-liu-4980** [comment]
您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了

**Comment by AlexYzhov** [comment]
> @JasonDENHJD
> 您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了

你好，我最近才解决RT1052的下载算法和XIP，还没有调过CSI。建议使用KSDK时仔细阅读RT1052的Reference Manual，会有收获！

**Comment by jason-liu-4980** [comment]
> @AlexYzhov
> > @JasonDENHJD
> > 您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了
> 
> 你好，我最近才解决RT1052的下载算法和XIP，还没有调过CSI。建议使用KSDK时仔细阅读RT1052的Reference Manual，会有收获！
> 

RM只有寄存器，官网SDK手册只有driver层，例程用的HAL层，然后CSI还涉及到图像数组不能被缓存命中，这样又涉及到分散加载文件，麻烦的很。我目前还是继续用KV58了，再次感谢您分享的KV58工程，尤其是摄像头DMA和FTM精度这两个部分。另外问一下您今年还做车么233？

**Comment by AlexYzhov** [comment]
> @JasonDENHJD
> > @AlexYzhov
> > > @JasonDENHJD
> > > 您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了
> > 
> > 你好，我最近才解决RT1052的下载算法和XIP，还没有调过CSI。建议使用KSDK时仔细阅读RT1052的Reference Manual，会有收获！
> > 
> 
> RM只有寄存器，官网SDK手册只有driver层，例程用的HAL层，然后CSI还涉及到图像数组不能被缓存命中，这样又涉及到分散加载文件，麻烦的很。我目前还是继续用KV58了，再次感谢您分享的KV58工程，尤其是摄像头DMA和FTM精度这两个部分。另外问一下您今年还做车么233？

KSDK的HAL库写的比较复杂(这点好像每家都一样)，我个人不太愿意去折腾。driver层的话函数其实也不多，对照RM捋清楚CSI的硬件架构，配起来应该也挺快的。我今年不参加比赛。

**Comment by AlexYzhov** [comment]
> @JasonDENHJD
> 您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了

你好 CSI最近写完了，适配了MT9V034。已经commit到我的github repo

**Comment by jason-liu-4980** [comment]
> @AlexYzhov
> > @JasonDENHJD
> > 您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了
> 
> 你好 CSI最近写完了，适配了MT9V034。已经commit到我的github repo


> @AlexYzhov
> > @JasonDENHJD
> > 您好，您的KV58工程对我来说受益匪浅，让我初步认识KSDK，最近我发现您Github上发了一个空的RT1050的Repo，不知道您现在RT1050的CSI写的如何了呢？我由于基础不足，已经卡在CSI上好久了
> 
> 你好 CSI最近写完了，适配了MT9V034。已经commit到我的github repo

万分感谢，现在我的KV58的车已经基本能跑了，等校赛结束后准备移到RT1052上试试
